### PR TITLE
fix(pjs-signer): ensure payload to be the same as PJS api

### LINKED ISSUE #480: PAPI transactions make Nova crash (part 2)
Hey frens,

Adding a mortality to transactions didn't fix the Nova crashes when submitting a tx.

On the below screenshot is the background process's log of talisman when running in dev mode. There we see the SignerPayloadJSON object sent by the dapp clearly. 

First transaction is a xcm transaction initiated with polkadot.js api (from app.talisman.xyz)
Second transaction is a swap initiated with PAPI (from kheopswap.xyz)

2 main differences : 
- the left padding with 0s on fields that contain a number encoded as hex
- tip property is missing on PAPI's payload
- not sure about this one but the transaction version value is different, i would have expected the last characters to be the same on both

image

I hope this helps

### PR DESCRIPTION
**Pull request by carlosala**
Closes #480

### CODE REVIEW

File: packages/signers/pjs-signer/src/pjs-signed-extensions-mappers.ts [hunk 1]
```diff
@@ -14,9 +14,13 @@ type SignedExtension = {
...
 
-const toPjsHex = (value: number | bigint) => {
-  const inner = value.toString(16)
-  return "0x" + (inner.length % 2 ? "0" : "") + inner
+const toPjsHex = (value: number | bigint, minByteLen?: number) => {
+  let inner = value.toString(16)
+  inner = (inner.length % 2 ? "0" : "") + inner
+  if (minByteLen && minByteLen - inner.length / 2 > 0) {
+    inner = "00".repeat(minByteLen - inner.length / 2) + inner
+  }
```
Comment (josepot) [inline packages/signers/pjs-signer/src/pjs-signed-extensions-mappers.ts:22]: nit:
```suggestion
  const nPaddedBytes = Math.max(0, (minByteLen || 0) - inner.length / 2)
  inner = "00".repeat(nPaddedBytes) + inner
```

File: packages/signers/pjs-signer/src/pjs-signed-extensions-mappers.ts [hunk 2]
```diff
@@ -28,13 +32,14 @@ export const CheckGenesis = ({
 export const CheckNonce = ({
   value,
 }: SignedExtension): { nonce: HexString } => {
-  return { nonce: toPjsHex(compact.dec(value)) }
+  // nonce is a u32 in pjs => 4 bytes
```
Comment (josepot) [inline packages/signers/pjs-signer/src/pjs-signed-extensions-mappers.ts:35]: only god knows why, because when encoded in the sign-extension is a compact... 🤷

Thanks for adding the comment!

**Review by josepot — APPROVED** [review]
LGTM! Thanks!

File: packages/signers/pjs-signer/src/pjs-signed-extensions-mappers.ts [hunk 3]
```diff
@@ -14,9 +14,13 @@ type SignedExtension = {
...
-const toPjsHex = (value: number | bigint) => {
-  const inner = value.toString(16)
-  return "0x" + (inner.length % 2 ? "0" : "") + inner
+const toPjsHex = (value: number | bigint, minByteLen?: number) => {
+  let inner = value.toString(16)
+  inner = (inner.length % 2 ? "0" : "") + inner
+  if (minByteLen && minByteLen - inner.length / 2 > 0) {
+    inner = "00".repeat(minByteLen - inner.length / 2) + inner
+  }
+  return "0x" + inner
```
Comment (josepot) [inline packages/signers/pjs-signer/src/pjs-signed-extensions-mappers.ts:23]: nit:
```suggestion
  const nPaddedBytes = Math.max(0, (minByteLen || 0) - inner.length / 2)
  return "0x" + "00".repeat(nPaddedBytes) + inner
```
