### PR TITLE
fix: handle "exotic" extrinsics

### LINKED ISSUE #807: Cannot estimate fee for Moonbeam
I'm trying to make a transfer in Moonbeam and before that I need to estimate the fee.
```js
  getTransferKeepAliveTx(api: TypedApi<typeof glmr>, destination: Address, amount: BigInt) {
    return api.tx.Balances.transfer_keep_alive({
      value: amount,
      dest: destination,
    });
  }

  // api is typed for Moonbeam
  // dest accepts HexString
  getTransferKeepAliveTx(api, '0x6F21E1C5234eC2DA8019632d4836fFCC2379DbA7', 1n);
```
Everything seems fine at this point, but when I do
```js
  tx.getEstimatedFees(destination);
  // or because it accepts Uint8Array or SS58String
  // which is not the case for "0x6F21E1C5234eC2DA8019632d4836fFCC2379DbA7"
  tx.getEstimatedFees(stringToU8a (destination));
```
It fails with error
```bash
OperationError: Execution failed: Execution aborted due to panic: panicked at /build/runtime/moonbeam/src/lib.rs:1549:1:
Bad input data provided to account_nonce: Input buffer has still data left after decoding!
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x6a1c - <unknown>!rust_begin_unwind
    1: 0x36d0 - <unknown>!core::panicking::panic_fmt::h7d22643b0becf577
    2: 0x594e5a - <unknown>!AccountNonceApi_account_nonce
    at Object.next (polkadot-api.js?v=ce55e648:2380:17)
    at Object.next (polkadot-api.js?v=ce55e648:2313:58)
    at Object.onAllFollowEventsNext [as next] (polkadot-api.js?v=ce55e648:2566:30)
    at Object.next (polkadot-api.js?v=ce55e648:2313:58)
    at onMessage (polkadot-api.js?v=ce55e648:2738:23)
```

Also I've looked into `getEstimatedFees` and "Sr25519" looks wrong for Moonbeam signer, doesn't it?
```js
const getPaymentInfo = async (from2, _options) => {
      const fakeSigner = getPolkadotSigner(
        from2 instanceof Uint8Array ? from2 : accountIdEnc(from2),
        "Sr25519",
        getFakeSignature
      );
      // ... rest of the function
};
```

`polkadot-api` version: 1.6.1

### PR DESCRIPTION
**Pull request by josepot**
Fixes #807 and #813. It also fixes an unreported issue which is that PAPI can now be used for creating transactions on Hydration, which also uses an "exotic" extrinsic.

This PR basically accounts for what I have coined as "exotic" extrinsics, which are those that differ from the Polkadot standard extrinsic. Namely, this means supporting extrinsics for "ethereum-like" chains like Moonbeam, Mythos, etc, and also chains like Hydration which don't expect an enum when passing the public key of the signer.

### CODE REVIEW

File: packages/signers/pjs-signer/src/from-pjs-account.ts [hunk 1]
```diff
@@ -24,13 +22,8 @@ export const getAddressFormat = (metadata: V14 | V15): number => {
...
 
-const versionCodec = enhanceEncoder(
-  u8.enc,
-  (value: { signed: boolean; version: number }) =>
-    (+!!value.signed << 7) | value.version,
-)
-
-const getPublicKey = AccountId().enc
+const getPublicKey = (address: string) =>
+  address.startsWith("0x") ? fromHex(address) : AccountId().enc(address)
```
Comment (carlosala) [inline packages/signers/pjs-signer/src/from-pjs-account.ts:26]: We could maybe use the hex regex instead to ensure that addresses without `0x` pass as well. There is a very little chance that a polkadot address passes the test though.

File: packages/signers/signers-common/src/v4.ts [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+  let address: LookupEntry
+  let signature: LookupEntry
+  if ("address" in extrinsic) {
+    address = getLookup(extrinsic.address)
+    signature = getLookup(extrinsic.signature)
+  } else {
+    const extLkup = getLookup(extrinsic.type)
+    if (extLkup.type !== "struct") throw unkownSignerType()
+    address = extLkup.value["Address"]
+    signature = extLkup.value["Signature"]
```
Comment (carlosala) [inline packages/signers/signers-common/src/v4.ts:34]: This won't work. The types are in the `params` section of the metadata, and the lookupFn does not help since it does not expose the `params`, raw metadata has to be used instead. Implementation example: https://github.com/polkadot-api/polkadot-api/blob/8325515664dd42220992622219a29ca3ba81ce75/packages/tx-utils/src/decode-extrinsic.ts#L47-L53

**Review by carlosala — COMMENTED** [review]
Just some little comments, good work! 🚀

**Review by carlosala — APPROVED** [review]
LGTM! 🚀
