### PR TITLE
fix(cli): download metadata in parallel plus generate all

### LINKED ISSUE #511: Parallelize downloads when running papi update
Currently in case there are multiple chains registered in `polkadot-api.json`, the `papi update` command processes chains one by one, sequentially.
Since each metadata download can take a pretty long time, the whole process can be very long. 
For example it took 2m20s on my last run (10 chains).

It would be nice if all downloads could be parallelized, to make runs faster.

### PR DESCRIPTION
**Pull request by josepot**
Closes #511 and improves the post-update `generate`.

### CODE REVIEW

File: packages/cli/src/commands/update.ts [hunk 1]
```diff
@@ -12,22 +12,19 @@ export async function update(
...
       if (keysInput !== undefined) {
         console.warn(`Key ${key} doesn't have a metadata file to update`)
       }
 
-      spinner.stop()
-      continue
+      return
     }
 
     const metadata = await getMetadata(entry as EntryConfig)
```
Comment (voliva) [inline packages/cli/src/commands/update.ts:30]: I think we need to be careful, this function is not prepared to be run in parallel - It's creating [one webworker](https://github.com/polkadot-api/polkadot-api/blob/main/packages/cli/src/metadata.ts#L27) with [one instance of smoldot](https://github.com/polkadot-api/polkadot-api/blob/main/packages/cli/src/smolldot-worker.ts) every time it's being called.

It probably works with a low amount of chains, but it might blow up on resources with a bigger amount.

This part needs to be improved, also the list of "known chains" is [hardcoded ](https://github.com/polkadot-api/polkadot-api/blob/main/packages/cli/src/well-known-chains.ts) to the few we knew back then
