### PR TITLE
fix: values typed as `FixedSizeBinary` is only an instance of `Binary`

### LINKED ISSUE #582: Values typed as `FixedSizeBinary` is only an instance of `Binary`
## Expected

```ts
const hash: FixedSizeBinary<32> = await api.query.System.ParentHash.getValue();

console.log(hash instanceof FixedSizeBinary); // true
```

## Actual

```ts
// Typed as `FixedSizeBinary<32>`
// but at runtime, return an instance of just `Binary`
const hash: FixedSizeBinary<32> = await api.query.System.ParentHash.getValue();

console.log(hash instanceof FixedSizeBinary); // false
```

### PR DESCRIPTION
**Pull request by tien**
Fixes #582

### CODE REVIEW

File: packages/substrate-bindings/src/codecs/scale/Binary.ts [hunk 1]
```diff
@@ -54,7 +54,10 @@ const enc = (nBytes?: number): Encoder<Binary> => {
 
 const dec = (nBytes?: number): Decoder<Binary> => {
   const _dec = Bytes.dec(nBytes)
-  return (value) => Binary.fromBytes(_dec(value))
+  return (value) =>
+    nBytes === undefined
+      ? Binary.fromBytes(_dec(value))
+      : FixedSizeBinary.fromBytes(_dec(value))
```
Comment (josepot) [inline packages/substrate-bindings/src/codecs/scale/Binary.ts:60]: small nit:

```suggestion
  const Bin = nBytes == null ? Binary : FixedSizeBinary
  return (value) => Bin.fromBytes(_dec(value))
```

**Review by josepot — APPROVED** [review]
I added a tiny nit. Otherwise, LGTM!

Thanks a lot @tien !

File: packages/substrate-bindings/src/codecs/scale/Binary.ts (hunk 1 above)
Comment (josepot) [reply packages/substrate-bindings/src/codecs/scale/Binary.ts:60]: FWIW: the `== null` is a trick used in libraries (which I wouldn't use when working on a top-level App) that produces `true` if the value is `undefined` or `null` and `false` otherwise. It has the advantage that it produces slightly smaller bundle sizes 🙂.

**Review by voliva — APPROVED** [review]
Thanks a lot for this! I also agree it is expected that if something is of type `FixedSizeBinary`, which is a class, then it should also be `instanceof FixedSizeBinary`

🚀
