### PR TITLE
fix: replace instanceof with shape checks

### LINKED ISSUE #1212: Incompatible runtime entry Storage
Getting recently tons of Incompatible runtime entry Storage. Any breaking change on your side ? 

```
Error: Incompatible runtime entry Storage(Stableswap.AssetTradability)
    at incompatibleError (/node_modules/polkadot-api/src/storage.ts:285:5)
    at <anonymous> (/node_modules/polkadot-api/src/storage.ts:332:21)
    at <anonymous> (/node_modules/polkadot-api/node_modules/@polkadot-api/observable-client/src/chainHead/chainHead.ts:312:25)
```

Update:

Seems like 0.20.x is rotten .. last working version 0.19.2

### PR DESCRIPTION
**Pull request by voliva**
Closes #1212

### CODE REVIEW

File: packages/metadata-compatibility/src/isCompatible.ts [hunk 1]
```diff
@@ -42,7 +41,9 @@ export function isCompatible(
       return checkTerminal(destNode)
     case "binary":
       return (
-        value instanceof Binary &&
+        typeof value === "object" &&
+        value &&
+        "asBytes" in value &&
```
Comment (carlosala) [inline packages/metadata-compatibility/src/isCompatible.ts]: shorter nit
```suggestion
        value != null &&
        typeof value.asBytes === "function" &&
```

**Review by carlosala — APPROVED** [review]
LGTM! 🚀
