### PR TITLE
fix: `file:` protocol breaks yarn immutable installation

### LINKED ISSUE #597: `file:` protocol break `yarn install --immutable`
Since Yarn's lockfile will use the entire content of the `file` dependency to compute its hash value, a clean installation from CI will result in a lockfile update, breaking `yarn install --immutable`.

### PR DESCRIPTION
**Pull request by tien**
Fixes #597

Yarn 2 has a [portal](https://yarnpkg.com/protocol/portal) protocol, designed specifically for this usecase.

### CODE REVIEW

**Comment by tien** [comment]
This unfortunately won't work with Yarn 1 though :(

File: packages/cli/src/commands/generate.ts [hunk 1]
```diff
@@ -87,8 +87,23 @@ async function cleanDescriptorsPackage(path: string) {
...
+      return "file"
+    }
+
+    const yarnVersion = await getNpmVersion(packageManager)
+    const yarnMajorVersion = Number(yarnVersion.split(".").at(0))
+
+    return yarnMajorVersion >= 2 ? "portal" : "file"
+  })()
+
+  const packageSource = `${protocol}:${path}`
```
Comment (voliva) [inline packages/cli/src/commands/generate.ts:106]: I think it will be better if this is moved out into a separate function, so this body ends up like

```ts
  const packageJson = await readPackage()
  const protocol = await getPackageProtocol()
  const packageSource = `${protocol}:${path}`
```

(I don't mind merging both awaits with a Promise.all, it sacrifices readability but wins on performance. I'm undecided on this one 😄)

**Review by voliva — CHANGES_REQUESTED** [review]
Thanks for raising, investigating and fixing it!

Just one comment to keep things a bit tidier. I appreciate your effort!

File: packages/cli/src/commands/generate.ts (hunk 1 above)
Comment (tien) [reply packages/cli/src/commands/generate.ts]: Hey, that make sense, I've extracted this to a function. For the `Promise.all` part, for me that is perfectly readable and much more performance, but do let me know if you decide otherwise 🙏

**Review by voliva — APPROVED** [review]
